/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/pages/web/webinfo.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '../../../../src/pages/web/webinfo.routing';
import * as import4 from '@angular/core/src/di/injector';
import * as import5 from './webinfo.ngfactory';
import * as import6 from './login/login.ngfactory';
import * as import7 from '../../../../src/pages/web/webinfo';
import * as import8 from '../../../../src/pages/web/login/login';
import * as import9 from '@angular/router/src/router_config_loader';
class WebInfoModuleInjector extends import0.NgModuleInjector<import1.WebInfoModule> {
  _RouterModule_0:import2.RouterModule;
  _WebInfoRoutingModule_1:import3.WebInfoRoutingModule;
  _WebInfoModule_2:import1.WebInfoModule;
  __ROUTES_3:any[];
  constructor(parent:import4.Injector) {
    super(parent,[
      import5.WebInfoPageNgFactory,
      import6.LoginInfoPageNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_3():any[] {
        if ((this.__ROUTES_3 == null)) { (this.__ROUTES_3 = [[{
          path: 'web',
          component: import7.WebInfoPage,
          children: [
            {
              path: 'login',
              component: import8.LoginInfoPage
            }
            ,
            {
              path: '',
              redirectTo: 'login',
              pathMatch: 'full'
            }

          ]

        }
    ]]); }
    return this.__ROUTES_3;
  }
  createInternal():import1.WebInfoModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._WebInfoRoutingModule_1 = new import3.WebInfoRoutingModule();
    this._WebInfoModule_2 = new import1.WebInfoModule();
    return this._WebInfoModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.WebInfoRoutingModule)) { return this._WebInfoRoutingModule_1; }
    if ((token === import1.WebInfoModule)) { return this._WebInfoModule_2; }
    if ((token === import9.ROUTES)) { return this._ROUTES_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const WebInfoModuleNgFactory:import0.NgModuleFactory<import1.WebInfoModule> = new import0.NgModuleFactory(WebInfoModuleInjector,import1.WebInfoModule);