/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/web/app.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '../../../../src/app/web/app.routing';
import * as import4 from '@angular/common/src/common_module';
import * as import5 from '@angular/core/src/application_module';
import * as import6 from '@angular/platform-browser/src/browser';
import * as import7 from '../../../../src/pages/web/webinfo.routing';
import * as import8 from '../../../../src/pages/web/webinfo.module';
import * as import9 from '@angular/common/src/location/location';
import * as import10 from '@angular/router/src/url_tree';
import * as import11 from '@angular/core/src/application_init';
import * as import12 from '@angular/core/src/testability/testability';
import * as import13 from '@angular/core/src/application_ref';
import * as import14 from '@angular/router/src/router_outlet_map';
import * as import15 from '@angular/core/src/linker/compiler';
import * as import16 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import17 from '@angular/router/src/router_preloader';
import * as import18 from '@angular/common/src/localization';
import * as import19 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import20 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import21 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import22 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import23 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import24 from '@angular/core/src/animation/animation_queue';
import * as import25 from '@angular/core/src/linker/view_utils';
import * as import26 from '@angular/platform-browser/src/browser/title';
import * as import27 from '@angular/core/src/di/injector';
import * as import28 from './app.component.ngfactory';
import * as import29 from '../../pages/web/webinfo.ngfactory';
import * as import30 from '../../pages/web/login/login.ngfactory';
import * as import31 from '@angular/common/src/location/platform_location';
import * as import32 from '@angular/common/src/location/location_strategy';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from '../../../../src/app/web/app.component';
import * as import35 from '../../../../src/pages/web/webinfo';
import * as import36 from '../../../../src/pages/web/login/login';
import * as import37 from '@angular/router/src/url_handling_strategy';
import * as import38 from '@angular/router/src/route_reuse_strategy';
import * as import39 from '@angular/core/src/i18n/tokens';
import * as import40 from '@angular/core/src/application_tokens';
import * as import41 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import42 from '@angular/platform-browser/src/dom/events/key_events';
import * as import43 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import44 from '@angular/router/src/router';
import * as import45 from '@angular/core/src/console';
import * as import46 from '@angular/core/src/error_handler';
import * as import47 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import48 from '@angular/router/src/router_config_loader';
import * as import49 from '@angular/router/src/router_state';
import * as import50 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import51 from '@angular/platform-browser/src/dom/animation_driver';
import * as import52 from '@angular/core/src/render/api';
import * as import53 from '@angular/core/src/security';
import * as import54 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import55 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class WebModuleInjector extends import0.NgModuleInjector<import1.WebModule> {
  _ROUTER_FORROOT_GUARD_0:any;
  _RouterModule_1:import2.RouterModule;
  _AppRoutingModule_2:import3.AppRoutingModule;
  _CommonModule_3:import4.CommonModule;
  _ApplicationModule_4:import5.ApplicationModule;
  _BrowserModule_5:import6.BrowserModule;
  _WebInfoRoutingModule_6:import7.WebInfoRoutingModule;
  _WebInfoModule_7:import8.WebInfoModule;
  _WebModule_8:import1.WebModule;
  __ROUTER_CONFIGURATION_9:any;
  __LocationStrategy_10:any;
  __Location_11:import9.Location;
  __UrlSerializer_12:import10.DefaultUrlSerializer;
  __ErrorHandler_13:any;
  __RouterInitializer_14:import2.RouterInitializer;
  __APP_INITIALIZER_15:any[];
  __ApplicationInitStatus_16:import11.ApplicationInitStatus;
  __Testability_17:import12.Testability;
  _ApplicationRef__18:import13.ApplicationRef_;
  __ApplicationRef_19:any;
  __RouterOutletMap_20:import14.RouterOutletMap;
  __Compiler_21:import15.Compiler;
  __NgModuleFactoryLoader_22:import16.SystemJsNgModuleLoader;
  __ROUTES_23:any[];
  __Router_24:any;
  __ActivatedRoute_25:any;
  _NoPreloading_26:import17.NoPreloading;
  _PreloadingStrategy_27:any;
  _RouterPreloader_28:import17.RouterPreloader;
  __PreloadAllModules_29:import17.PreloadAllModules;
  __NgProbeToken_30:any[];
  __ROUTER_INITIALIZER_31:any;
  __APP_BOOTSTRAP_LISTENER_32:any[];
  __LOCALE_ID_33:any;
  __NgLocalization_34:import18.NgLocaleLocalization;
  __APP_ID_35:any;
  __DOCUMENT_36:any;
  __HAMMER_GESTURE_CONFIG_37:import19.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_38:any[];
  __EventManager_39:import20.EventManager;
  _DomSharedStylesHost_40:import21.DomSharedStylesHost;
  __AnimationDriver_41:any;
  __DomRootRenderer_42:import22.DomRootRenderer_;
  __RootRenderer_43:any;
  __DomSanitizer_44:import23.DomSanitizerImpl;
  __Sanitizer_45:any;
  __AnimationQueue_46:import24.AnimationQueue;
  __ViewUtils_47:import25.ViewUtils;
  __IterableDiffers_48:any;
  __KeyValueDiffers_49:any;
  __SharedStylesHost_50:any;
  __Title_51:import26.Title;
  constructor(parent:import27.Injector) {
    super(parent,[
      import28.MyAppNgFactory,
      import29.WebInfoPageNgFactory,
      import30.LoginInfoPageNgFactory
    ]
    ,[import28.MyAppNgFactory]);
  }
  get _ROUTER_CONFIGURATION_9():any {
    if ((this.__ROUTER_CONFIGURATION_9 == null)) { (this.__ROUTER_CONFIGURATION_9 = {useHash: true}); }
    return this.__ROUTER_CONFIGURATION_9;
  }
  get _LocationStrategy_10():any {
    if ((this.__LocationStrategy_10 == null)) { (this.__LocationStrategy_10 = import2.provideLocationStrategy(this.parent.get(import31.PlatformLocation),this.parent.get(import32.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_9)); }
    return this.__LocationStrategy_10;
  }
  get _Location_11():import9.Location {
    if ((this.__Location_11 == null)) { (this.__Location_11 = new import9.Location(this._LocationStrategy_10)); }
    return this.__Location_11;
  }
  get _UrlSerializer_12():import10.DefaultUrlSerializer {
    if ((this.__UrlSerializer_12 == null)) { (this.__UrlSerializer_12 = new import10.DefaultUrlSerializer()); }
    return this.__UrlSerializer_12;
  }
  get _ErrorHandler_13():any {
    if ((this.__ErrorHandler_13 == null)) { (this.__ErrorHandler_13 = import6.errorHandler()); }
    return this.__ErrorHandler_13;
  }
  get _RouterInitializer_14():import2.RouterInitializer {
    if ((this.__RouterInitializer_14 == null)) { (this.__RouterInitializer_14 = new import2.RouterInitializer(this)); }
    return this.__RouterInitializer_14;
  }
  get _APP_INITIALIZER_15():any[] {
    if ((this.__APP_INITIALIZER_15 == null)) { (this.__APP_INITIALIZER_15 = [import2.getAppInitializer(this._RouterInitializer_14)]); }
    return this.__APP_INITIALIZER_15;
  }
  get _ApplicationInitStatus_16():import11.ApplicationInitStatus {
    if ((this.__ApplicationInitStatus_16 == null)) { (this.__ApplicationInitStatus_16 = new import11.ApplicationInitStatus(this._APP_INITIALIZER_15)); }
    return this.__ApplicationInitStatus_16;
  }
  get _Testability_17():import12.Testability {
    if ((this.__Testability_17 == null)) { (this.__Testability_17 = new import12.Testability(this.parent.get(import33.NgZone))); }
    return this.__Testability_17;
  }
  get _ApplicationRef_19():any {
    if ((this.__ApplicationRef_19 == null)) { (this.__ApplicationRef_19 = this._ApplicationRef__18); }
    return this.__ApplicationRef_19;
  }
  get _RouterOutletMap_20():import14.RouterOutletMap {
    if ((this.__RouterOutletMap_20 == null)) { (this.__RouterOutletMap_20 = new import14.RouterOutletMap()); }
    return this.__RouterOutletMap_20;
  }
  get _Compiler_21():import15.Compiler {
    if ((this.__Compiler_21 == null)) { (this.__Compiler_21 = new import15.Compiler()); }
    return this.__Compiler_21;
  }
  get _NgModuleFactoryLoader_22():import16.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_22 == null)) { (this.__NgModuleFactoryLoader_22 = new import16.SystemJsNgModuleLoader(this._Compiler_21,this.parent.get(import16.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_22;
  }
  get _ROUTES_23():any[] {
    if ((this.__ROUTES_23 == null)) { (this.__ROUTES_23 = [
        [{
          path: '',
          component: import34.MyApp
        }
      ],
        [{
          path: 'web',
          component: import35.WebInfoPage,
          children: [
            {
              path: 'login',
              component: import36.LoginInfoPage
            }
            ,
            {
              path: '',
              redirectTo: 'login',
              pathMatch: 'full'
            }

          ]

        }
      ]
    ]
    ); }
    return this.__ROUTES_23;
  }
  get _Router_24():any {
    if ((this.__Router_24 == null)) { (this.__Router_24 = import2.setupRouter(this._ApplicationRef_19,this._UrlSerializer_12,this._RouterOutletMap_20,this._Location_11,this,this._NgModuleFactoryLoader_22,this._Compiler_21,this._ROUTES_23,this._ROUTER_CONFIGURATION_9,this.parent.get(import37.UrlHandlingStrategy,(null as any)),this.parent.get(import38.RouteReuseStrategy,(null as any)))); }
    return this.__Router_24;
  }
  get _ActivatedRoute_25():any {
    if ((this.__ActivatedRoute_25 == null)) { (this.__ActivatedRoute_25 = import2.rootRoute(this._Router_24)); }
    return this.__ActivatedRoute_25;
  }
  get _PreloadAllModules_29():import17.PreloadAllModules {
    if ((this.__PreloadAllModules_29 == null)) { (this.__PreloadAllModules_29 = new import17.PreloadAllModules()); }
    return this.__PreloadAllModules_29;
  }
  get _NgProbeToken_30():any[] {
    if ((this.__NgProbeToken_30 == null)) { (this.__NgProbeToken_30 = [import2.routerNgProbeToken()]); }
    return this.__NgProbeToken_30;
  }
  get _ROUTER_INITIALIZER_31():any {
    if ((this.__ROUTER_INITIALIZER_31 == null)) { (this.__ROUTER_INITIALIZER_31 = import2.getBootstrapListener(this._RouterInitializer_14)); }
    return this.__ROUTER_INITIALIZER_31;
  }
  get _APP_BOOTSTRAP_LISTENER_32():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_32 == null)) { (this.__APP_BOOTSTRAP_LISTENER_32 = [this._ROUTER_INITIALIZER_31]); }
    return this.__APP_BOOTSTRAP_LISTENER_32;
  }
  get _LOCALE_ID_33():any {
    if ((this.__LOCALE_ID_33 == null)) { (this.__LOCALE_ID_33 = import5._localeFactory(this.parent.get(import39.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_33;
  }
  get _NgLocalization_34():import18.NgLocaleLocalization {
    if ((this.__NgLocalization_34 == null)) { (this.__NgLocalization_34 = new import18.NgLocaleLocalization(this._LOCALE_ID_33)); }
    return this.__NgLocalization_34;
  }
  get _APP_ID_35():any {
    if ((this.__APP_ID_35 == null)) { (this.__APP_ID_35 = import40._appIdRandomProviderFactory()); }
    return this.__APP_ID_35;
  }
  get _DOCUMENT_36():any {
    if ((this.__DOCUMENT_36 == null)) { (this.__DOCUMENT_36 = import6._document()); }
    return this.__DOCUMENT_36;
  }
  get _HAMMER_GESTURE_CONFIG_37():import19.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_37 == null)) { (this.__HAMMER_GESTURE_CONFIG_37 = new import19.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_37;
  }
  get _EVENT_MANAGER_PLUGINS_38():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_38 == null)) { (this.__EVENT_MANAGER_PLUGINS_38 = [
      new import41.DomEventsPlugin(),
      new import42.KeyEventsPlugin(),
      new import19.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_37)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_38;
  }
  get _EventManager_39():import20.EventManager {
    if ((this.__EventManager_39 == null)) { (this.__EventManager_39 = new import20.EventManager(this._EVENT_MANAGER_PLUGINS_38,this.parent.get(import33.NgZone))); }
    return this.__EventManager_39;
  }
  get _AnimationDriver_41():any {
    if ((this.__AnimationDriver_41 == null)) { (this.__AnimationDriver_41 = import6._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_41;
  }
  get _DomRootRenderer_42():import22.DomRootRenderer_ {
    if ((this.__DomRootRenderer_42 == null)) { (this.__DomRootRenderer_42 = new import22.DomRootRenderer_(this._DOCUMENT_36,this._EventManager_39,this._DomSharedStylesHost_40,this._AnimationDriver_41,this._APP_ID_35)); }
    return this.__DomRootRenderer_42;
  }
  get _RootRenderer_43():any {
    if ((this.__RootRenderer_43 == null)) { (this.__RootRenderer_43 = import43._createConditionalRootRenderer(this._DomRootRenderer_42,this.parent.get(import43.NgProbeToken,(null as any)),this._NgProbeToken_30)); }
    return this.__RootRenderer_43;
  }
  get _DomSanitizer_44():import23.DomSanitizerImpl {
    if ((this.__DomSanitizer_44 == null)) { (this.__DomSanitizer_44 = new import23.DomSanitizerImpl()); }
    return this.__DomSanitizer_44;
  }
  get _Sanitizer_45():any {
    if ((this.__Sanitizer_45 == null)) { (this.__Sanitizer_45 = this._DomSanitizer_44); }
    return this.__Sanitizer_45;
  }
  get _AnimationQueue_46():import24.AnimationQueue {
    if ((this.__AnimationQueue_46 == null)) { (this.__AnimationQueue_46 = new import24.AnimationQueue(this.parent.get(import33.NgZone))); }
    return this.__AnimationQueue_46;
  }
  get _ViewUtils_47():import25.ViewUtils {
    if ((this.__ViewUtils_47 == null)) { (this.__ViewUtils_47 = new import25.ViewUtils(this._RootRenderer_43,this._Sanitizer_45,this._AnimationQueue_46)); }
    return this.__ViewUtils_47;
  }
  get _IterableDiffers_48():any {
    if ((this.__IterableDiffers_48 == null)) { (this.__IterableDiffers_48 = import5._iterableDiffersFactory()); }
    return this.__IterableDiffers_48;
  }
  get _KeyValueDiffers_49():any {
    if ((this.__KeyValueDiffers_49 == null)) { (this.__KeyValueDiffers_49 = import5._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_49;
  }
  get _SharedStylesHost_50():any {
    if ((this.__SharedStylesHost_50 == null)) { (this.__SharedStylesHost_50 = this._DomSharedStylesHost_40); }
    return this.__SharedStylesHost_50;
  }
  get _Title_51():import26.Title {
    if ((this.__Title_51 == null)) { (this.__Title_51 = new import26.Title()); }
    return this.__Title_51;
  }
  createInternal():import1.WebModule {
    this._ROUTER_FORROOT_GUARD_0 = import2.provideForRootGuard(this.parent.get(import44.Router,(null as any)));
    this._RouterModule_1 = new import2.RouterModule(this._ROUTER_FORROOT_GUARD_0);
    this._AppRoutingModule_2 = new import3.AppRoutingModule();
    this._CommonModule_3 = new import4.CommonModule();
    this._ApplicationModule_4 = new import5.ApplicationModule();
    this._BrowserModule_5 = new import6.BrowserModule(this.parent.get(import6.BrowserModule,(null as any)));
    this._WebInfoRoutingModule_6 = new import7.WebInfoRoutingModule();
    this._WebInfoModule_7 = new import8.WebInfoModule();
    this._WebModule_8 = new import1.WebModule();
    this._ApplicationRef__18 = new import13.ApplicationRef_(this.parent.get(import33.NgZone),this.parent.get(import45.Console),this,this._ErrorHandler_13,this,this._ApplicationInitStatus_16,this.parent.get(import12.TestabilityRegistry,(null as any)),this._Testability_17);
    this._NoPreloading_26 = new import17.NoPreloading();
    this._PreloadingStrategy_27 = this._NoPreloading_26;
    this._RouterPreloader_28 = new import17.RouterPreloader(this._Router_24,this._NgModuleFactoryLoader_22,this._Compiler_21,this,this._PreloadingStrategy_27);
    this._DomSharedStylesHost_40 = new import21.DomSharedStylesHost(this._DOCUMENT_36);
    return this._WebModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_0; }
    if ((token === import2.RouterModule)) { return this._RouterModule_1; }
    if ((token === import3.AppRoutingModule)) { return this._AppRoutingModule_2; }
    if ((token === import4.CommonModule)) { return this._CommonModule_3; }
    if ((token === import5.ApplicationModule)) { return this._ApplicationModule_4; }
    if ((token === import6.BrowserModule)) { return this._BrowserModule_5; }
    if ((token === import7.WebInfoRoutingModule)) { return this._WebInfoRoutingModule_6; }
    if ((token === import8.WebInfoModule)) { return this._WebInfoModule_7; }
    if ((token === import1.WebModule)) { return this._WebModule_8; }
    if ((token === import2.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_9; }
    if ((token === import32.LocationStrategy)) { return this._LocationStrategy_10; }
    if ((token === import9.Location)) { return this._Location_11; }
    if ((token === import10.UrlSerializer)) { return this._UrlSerializer_12; }
    if ((token === import46.ErrorHandler)) { return this._ErrorHandler_13; }
    if ((token === import2.RouterInitializer)) { return this._RouterInitializer_14; }
    if ((token === import11.APP_INITIALIZER)) { return this._APP_INITIALIZER_15; }
    if ((token === import11.ApplicationInitStatus)) { return this._ApplicationInitStatus_16; }
    if ((token === import12.Testability)) { return this._Testability_17; }
    if ((token === import13.ApplicationRef_)) { return this._ApplicationRef__18; }
    if ((token === import13.ApplicationRef)) { return this._ApplicationRef_19; }
    if ((token === import14.RouterOutletMap)) { return this._RouterOutletMap_20; }
    if ((token === import15.Compiler)) { return this._Compiler_21; }
    if ((token === import47.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_22; }
    if ((token === import48.ROUTES)) { return this._ROUTES_23; }
    if ((token === import44.Router)) { return this._Router_24; }
    if ((token === import49.ActivatedRoute)) { return this._ActivatedRoute_25; }
    if ((token === import17.NoPreloading)) { return this._NoPreloading_26; }
    if ((token === import17.PreloadingStrategy)) { return this._PreloadingStrategy_27; }
    if ((token === import17.RouterPreloader)) { return this._RouterPreloader_28; }
    if ((token === import17.PreloadAllModules)) { return this._PreloadAllModules_29; }
    if ((token === import13.NgProbeToken)) { return this._NgProbeToken_30; }
    if ((token === import2.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_31; }
    if ((token === import40.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_32; }
    if ((token === import39.LOCALE_ID)) { return this._LOCALE_ID_33; }
    if ((token === import18.NgLocalization)) { return this._NgLocalization_34; }
    if ((token === import40.APP_ID)) { return this._APP_ID_35; }
    if ((token === import50.DOCUMENT)) { return this._DOCUMENT_36; }
    if ((token === import19.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_37; }
    if ((token === import20.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_38; }
    if ((token === import20.EventManager)) { return this._EventManager_39; }
    if ((token === import21.DomSharedStylesHost)) { return this._DomSharedStylesHost_40; }
    if ((token === import51.AnimationDriver)) { return this._AnimationDriver_41; }
    if ((token === import22.DomRootRenderer)) { return this._DomRootRenderer_42; }
    if ((token === import52.RootRenderer)) { return this._RootRenderer_43; }
    if ((token === import23.DomSanitizer)) { return this._DomSanitizer_44; }
    if ((token === import53.Sanitizer)) { return this._Sanitizer_45; }
    if ((token === import24.AnimationQueue)) { return this._AnimationQueue_46; }
    if ((token === import25.ViewUtils)) { return this._ViewUtils_47; }
    if ((token === import54.IterableDiffers)) { return this._IterableDiffers_48; }
    if ((token === import55.KeyValueDiffers)) { return this._KeyValueDiffers_49; }
    if ((token === import21.SharedStylesHost)) { return this._SharedStylesHost_50; }
    if ((token === import26.Title)) { return this._Title_51; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__18.ngOnDestroy();
    this._RouterPreloader_28.ngOnDestroy();
    this._DomSharedStylesHost_40.ngOnDestroy();
  }
}
export const WebModuleNgFactory:import0.NgModuleFactory<import1.WebModule> = new import0.NgModuleFactory(WebModuleInjector,import1.WebModule);